import '@carbon/react/index.scss';
import './global.scss';
import { Inter } from 'next/font/google'
import { Nav } from './nav.tsx'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Mental Desk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Nav /> 
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  )
}

