import '@carbon/react/index.scss';
import './global.scss';
import { Nav } from './nav'
import { Footer } from './Footer'


export const metadata = {
  title: 'Mental Desk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
        <div className="layout">
          <Nav />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}

